### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ecchirealm** [taraglo/video-downloader#1]
File "D:\test\video-downloader-main\main.py", line 83, in <module>
    ff_driver = webdriver.Firefox(options=firefox_profile)
  File "C:\Users\test\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 197, in __init__
    super().__init__(command_executor=executor, options=options, keep_alive=True)
  File "C:\Users\test\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 288, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\test\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 381, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\test\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "C:\Users\test\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line

**Comment by taraglo** [comment]
You need to install Firefox browser. If you already have it installed, then it seems like it can't find the Firefox executable.
Check [this](https://stackoverflow.com/a/64908883) stackoverflow thread for more details.

**Comment by ecchirealm** [comment]
I set that up, still not working

**Comment by ecchirealm** [comment]
if you can help me set the bot up I can send you $ let me know, you can contact me at ecchirealm@gmail.com

**Comment by taraglo** [comment]
Well, I need more details on where/how you're running that script. Do you get the exact same error after installing Firefox? Did you try using custom path to firefox.exe file using `option` like shown in the stackoverflow answer?

**Comment by ecchirealm** [comment]
yea, chromedriver works though so if you can make an edit to have it work with that, it would fix it I think I setup geckodriver and binary firefox path but still doesn't work

**Comment by taraglo** [comment]
if you want to use Chrome, then change line [83](https://github.com/taraglo/video-downloader/blob/main/main.py#L83) of `main.py` to the following:
```
ff_driver = webdriver.Chrome()
```
If it doesn't work, then specify the location to the chrome driver like the following:
```
ff_driver = webdriver.Chrome(executable_path=r"C:\path\to\chromedriver.exe")
```
Also, you can remove line [79 to 82](https://github.com/taraglo/video-downloader/blob/main/main.py#L79-L82) since they're no longer needed.

**Comment by ecchirealm** [comment]
Invalid URL: https://hqporner.com/hdporn/82041-seduced_by_my_stepmom.html

All videos downloaded successfully.
Process finished in 0.91 seconds

**Comment by ecchirealm** [comment]
ok I was able to figure it out thank you!

**Comment by ecchirealm** [comment]
let me know if you're able to make edits to the bot for a price, I need it to implement s3cmd put command

**Comment by ecchirealm** [comment]
when trying to go directly to URL - example (https://hqporner.com/hdporn/82041-seduced_by_my_stepmom.html) it returns an error

**Comment by ecchirealm** [comment]
but if you click on a link it's fine I think it needs to add a 'referer' (hqporner.com) when opening links on chromedriver/firefox so it doesn't return that error

**Comment by ecchirealm** [comment]
looks like they just added this cause before when going directly to url it would work
